config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get    '/',        to: 'home#index'
    resources :users
    resources :profile, only: %i[index update] do
      collection do
        get 'password'
        put 'update_password'
      end
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  address                :string
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  first_name             :string           not null
#  last_name              :string           not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  phone                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  zipcode                :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_phone                 (phone) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#
class User < ApplicationRecord
  include SpreadsheetArchitect

  validates :first_name, :last_name, length: { minimum: 2 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockab le, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def spreadsheet_columns
    %i[id email first_name last_name phone address zipcode]
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @search = User.all.ransack(params[:q])

    respond_to do |format|
      format.html { @pagy, @users = pagy(@search.result) }
      format.csv  { render csv: @search.result }
    end
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, status: :see_other, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/admins/users_controller.rb
# frozen_string_literal: true

class Admins::UsersController < Admins::BaseController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @search = User.all.ransack(params[:q])

    respond_to do |format|
      format.html { @pagy, @users = pagy(@search.result) }
      format.csv  { render csv: @search.result }
    end
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admins_users_path, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admins_users_path, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admins_users_url, status: :see_other, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/admins/users/_form.html.erb
<%= form_with(model: [:admins, user]) do |form| %>
  <div class="form-group row mb-2">
    <%= form.label :first_name, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.text_field :first_name, required: true, autocomplete: "first-name", class: "form-control" %>
      <%= tag.div user.errors[:first_name].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-group row mb-2">
    <%= form.label :last_name, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.text_field :last_name, required: true, autocomplete: "last-name", class: "form-control" %>
      <%= tag.div user.errors[:last_name].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-group row mb-2">
    <%= form.label :email, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.email_field :email, autocomplete: "email", class: "form-control" %>
      <%= tag.div user.errors[:email].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-group row mb-2">
    <%= form.label :password, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.password_field :password, required: true, autocomplete: "new-password", class: "form-control" %>
      <%= tag.div user.errors[:password].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password_confirmation, class: "form-label col-md-3 col-form-label" %>
    <div class="col-md px-0">
      <%= form.password_field :password_confirmation, required: true, autocomplete: "new-password", class: "form-control" %>
      <%= tag.div user.errors[:password_confirmation].first, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="form-footer">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", admins_users_path, class: "btn btn-white" %>
  </div>
<% end %>

app/views/admins/users/edit.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: "Editing user" do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admins_path %></li>
    <li class="breadcrumb-item"><%= link_to "Users", admins_users_path %></li>
    <li class="breadcrumb-item"><%= link_to @user.email, admins_user_path(@user) %></li>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="card-body">
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: "Users" do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admins_path %></li>
  <% end %>

  <%= render "page_header_actions" do %>
    <%= link_to "Filters", "#offcanvas_filters", "data-bs-toggle": "offcanvas", class: "btn btn-white" %>
    <%= link_to "New user", new_admins_user_path, class: "btn btn-primary" %>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="table-responsive">
        <table class="table table-vcenter table-nowrap card-table table-striped">
          <thead>
            <tr>
              <th><%= sort_link @search, :id %></th>
              <th><%= sort_link @search, :email %></th>
              <th><%= sort_link @search, :created_at %></th>
              <th class="w-1"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to user.id, admins_user_path(user) %></td>
                <td><%= user.email %></td>
                <td><%= l(user.created_at, format: :long) %></td>
                <td>
                  <%= link_to "View", admins_user_path(user), class: "btn btn-white btn-sm" %>
                  <%= link_to "Edit", edit_admins_user_path(user), class: "btn btn-white btn-sm" %>
                  <%= link_to "Delete", admins_user_path(user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, form_class: "d-inline", class: "btn btn-white btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex align-items-center fs-5">
        <div class="d-none d-md-block">
          <div>Download: <%= link_to "CSV", admins_users_path(format: :csv, q: request.params[:q]) %></div>
          <%= raw pagy_info(@pagy) %>
        </div>
        <div class="ms-auto">
          <%= render "pagination", pagy: @pagy %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="offcanvas_filters" tabindex="-1" class="offcanvas offcanvas-end">
  <div class="offcanvas-header">
    <h2 class="offcanvas-title">Filters</h2>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
  </div>
  <%= search_form_for @search, url: admins_users_path, class: "offcanvas-body" do |f| %>
    <%= f.label :email_cont, class: "form-label" %>
    <%= f.text_field :email_cont, class: "form-control mb-3" %>

    <%= f.label :created_at, class: "form-label" %>
    <div class="d-flex gap-1 mb-3">
      <%= f.date_field :created_at_gteq, class: "form-control" %>
      <%= f.date_field :created_at_lteq, class: "form-control" %>
    </div>

    <%= f.submit "Filter", class: "btn btn-primary" %>
    <%= link_to "Clear Filter", admins_users_path, class: "btn btn-white" %>
  <% end %>
</div>

app/views/admins/users/new.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: "New user" do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admins_path %></li>
    <li class="breadcrumb-item"><%= link_to "Users", admins_users_path %></li>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="card-body">
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<%= render "page_header" do %>
  <%= render "page_header_breadcrumb", title: @user.email do %>
    <li class="breadcrumb-item"><%= link_to "Admin", admins_path %></li>
    <li class="breadcrumb-item"><%= link_to "Users", admins_users_path %></li>
  <% end %>

  <%= render "page_header_actions" do %>
    <%= link_to "Edit user", edit_admins_user_path(@user), class: "btn btn-primary" %>
    <%= button_to "Delete user", edit_admins_user_path(@user), method: :delete, "data-confirm": "Are you sure?", form_class: "d-inline", class: "btn btn-white" %>
  <% end %>
<% end %>

<div class="page-body">
  <div class="container-xl">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">User details</h3>
      </div>
      <div class="card-body">
        <dl class="row">
          <dt class="col-md-3">Email</dt>
          <dd class="col-md-9"><%= @user.email %></dd>

          <dt class="col-md-3">Created at</dt>
          <dd class="col-md-9"><%= l(@user.created_at, format: :long) %></dd>

          <dt class="col-md-3">Updated at</dt>
          <dd class="col-md-9"><%= l(@user.updated_at, format: :long) %></dd>
        </dl>
      </div>
    </div>
  </div>
</div>